export const FETCH_TODO_START = "FETCH_TODO_START";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAIL = "FETCH_TODO_FAIL";

export const SUBMIT_TODO_START = "SUBMIT_TODO_START";
export const SUBMIT_TODO_SUCCESS = "SUBMIT_TODO_SUCCESS";
export const SUBMIT_TODO_FAIL = "SUBMIT_TODO_FAIL";

export const MARK_AS_COMPLETED_START = "MARK_AS_COMPLETED_START";
export const MARK_AS_COMPLETED_SUCCESS = "MARK_AS_COMPLETED_SUCCESS";
export const MARK_AS_COMPLETED_FAIL = "MARK_AS_COMPLETED_FAIL";

export const DELETE_TODO_START = "DELETE_TODO_START";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";

export const RESET_ERROR = "RESET_ERROR";

export const LOGOUT_USER_DATA = "LOGOUT_USER_DATA";
